save_every: 10000
print_every: 2000

dataset:
  name: mc2
  split: 1

train: 
  batch_size: 2
  optimizer: SGD
  epoch: 1500
  lr: 0.02
  momentum: 0.009
  weight_decay: 0.0
  clip_grad_norm: 10.0

wavenet: 
  input_size: 2048
  hidden_size: 128
  pooling_levels: "[1, 2, 3, 4]"

thres:
  w: 0.5
  hidden_size: 64

poc_loss:
  w: 0.1
  use_gt: False

att_len_loss:
  w: 0.5
  min: 0.6a
  max: 2.5f

att_smooth_loss:
  w: 0.25

centering_loss:
  w: 0.5

att_ranking_loss:
  w: 1.0
  nstable: True